//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.FamilyShow.Properties
{
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.FamilyShow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à 20-39.
        /// </summary>
        internal static string AgeGroupAdult
        {
            get
            {
                return ResourceManager.GetString("AgeGroupAdult", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à 40-64.
        /// </summary>
        internal static string AgeGroupMiddleAge
        {
            get
            {
                return ResourceManager.GetString("AgeGroupMiddleAge", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à 65+.
        /// </summary>
        internal static string AgeGroupSenior
        {
            get
            {
                return ResourceManager.GetString("AgeGroupSenior", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à ?.
        /// </summary>
        internal static string AgeGroupUnknown
        {
            get
            {
                return ResourceManager.GetString("AgeGroupUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0-19.
        /// </summary>
        internal static string AgeGroupYouth
        {
            get
            {
                return ResourceManager.GetString("AgeGroupYouth", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à *.*.
        /// </summary>
        internal static string AllExtension
        {
            get
            {
                return ResourceManager.GetString("AllExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à All Files (*.*).
        /// </summary>
        internal static string AllFiles
        {
            get
            {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à .familyx.
        /// </summary>
        internal static string DefaultFamilyExtension
        {
            get
            {
                return ResourceManager.GetString("DefaultFamilyExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à .ged.
        /// </summary>
        internal static string DefaultGedcomExtension
        {
            get
            {
                return ResourceManager.GetString("DefaultGedcomExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à This section can be used to provide more information about this person.  Write a story. Describe this person&apos;s accomplishments, likes/dislikes. Use the editor toolbar to change the formatting of the text, add bulleted lists, etc.
        ///To add photos for this person, simply drag them into the photo box on the bottom left.
        ///To remove this template text, click on the Edit button, select all of the text (CTRL+A), then press the Delete key..
        /// </summary>
        internal static string DefaultStory
        {
            get
            {
                return ResourceManager.GetString("DefaultStory", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à .xps.
        /// </summary>
        internal static string DefaultXpsExtension
        {
            get
            {
                return ResourceManager.GetString("DefaultXpsExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        internal static string Export
        {
            get
            {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à *.family;*.familyx.
        /// </summary>
        internal static string FamilyExtensions
        {
            get
            {
                return ResourceManager.GetString("FamilyExtensions", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family.Show Files (.familyx or .family).
        /// </summary>
        internal static string FamilyFiles
        {
            get
            {
                return ResourceManager.GetString("FamilyFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à *.family.
        /// </summary>
        internal static string FamilyV2Extension
        {
            get
            {
                return ResourceManager.GetString("FamilyV2Extension", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family.Show V2 Files (.family).
        /// </summary>
        internal static string FamilyV2Files
        {
            get
            {
                return ResourceManager.GetString("FamilyV2Files", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à *.familyx.
        /// </summary>
        internal static string FamilyV3Extension
        {
            get
            {
                return ResourceManager.GetString("FamilyV3Extension", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family.Show V3 Files (.familyx).
        /// </summary>
        internal static string FamilyV3Files
        {
            get
            {
                return ResourceManager.GetString("FamilyV3Files", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à *.ged.
        /// </summary>
        internal static string GedcomExtension
        {
            get
            {
                return ResourceManager.GetString("GedcomExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Failed.
        /// </summary>
        internal static string GedcomFailed
        {
            get
            {
                return ResourceManager.GetString("GedcomFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The GEDCOM file could not be imported..
        /// </summary>
        internal static string GedcomFailedMessage
        {
            get
            {
                return ResourceManager.GetString("GedcomFailedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gedcom Files (.ged).
        /// </summary>
        internal static string GedcomFiles
        {
            get
            {
                return ResourceManager.GetString("GedcomFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Edward_VII
        {
            get
            {
                object obj = ResourceManager.GetObject("Image_Edward_VII", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Edward_VIII
        {
            get
            {
                object obj = ResourceManager.GetObject("Image_Edward_VIII", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Elizabeth_II
        {
            get
            {
                object obj = ResourceManager.GetObject("Image_Elizabeth_II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_George_V
        {
            get
            {
                object obj = ResourceManager.GetObject("Image_George_V", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_George_VI
        {
            get
            {
                object obj = ResourceManager.GetObject("Image_George_VI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Margaret_Rose
        {
            get
            {
                object obj = ResourceManager.GetObject("Image_Margaret_Rose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Prince_Charles
        {
            get
            {
                object obj = ResourceManager.GetObject("Image_Prince_Charles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Prince_Henry
        {
            get
            {
                object obj = ResourceManager.GetObject("Image_Prince_Henry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Prince_William
        {
            get
            {
                object obj = ResourceManager.GetObject("Image_Prince_William", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Princess_Diana
        {
            get
            {
                object obj = ResourceManager.GetObject("Image_Princess_Diana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        internal static string Import
        {
            get
            {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à *.jpg.
        /// </summary>
        internal static string JpegExtension
        {
            get
            {
                return ResourceManager.GetString("JpegExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family.Show Files (.jpg).
        /// </summary>
        internal static string JpegFiles
        {
            get
            {
                return ResourceManager.GetString("JpegFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] KennedySampleFile
        {
            get
            {
                object obj = ResourceManager.GetObject("KennedySampleFile", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The method or operation is not implemented..
        /// </summary>
        internal static string NotImplemented
        {
            get
            {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string NotSaved
        {
            get
            {
                return ResourceManager.GetString("NotSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The current family has not been saved. Do you want to save?.
        /// </summary>
        internal static string NotSavedMessage
        {
            get
            {
                return ResourceManager.GetString("NotSavedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        internal static string Open
        {
            get
            {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à *.png.
        /// </summary>
        internal static string PngExtension
        {
            get
            {
                return ResourceManager.GetString("PngExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family.Show Files (.png).
        /// </summary>
        internal static string PngFiles
        {
            get
            {
                return ResourceManager.GetString("PngFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resources.
        /// </summary>
        internal static string ResourcesString
        {
            get
            {
                return ResourceManager.GetString("ResourcesString", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save As.
        /// </summary>
        internal static string SaveAs
        {
            get
            {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skins.
        /// </summary>
        internal static string Skins
        {
            get
            {
                return ResourceManager.GetString("Skins", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs18\f2\cf0 \cf0\ql{\f2 {\ltrch Camilla, Duchess of Cornwall, born in 1947, second wife of Charles, prince of Wales. The former Camilla Parker Bowles and Prince Charles, heir to the British throne, were married on April 9, 2005, in a civil ceremony in Windsor, England.}\li0\ri0\sa0\sb0\fi0\ql\par} [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Story_Camilla_Shand
        {
            get
            {
                return ResourceManager.GetString("Story_Camilla_Shand", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs18\f2\cf0 \cf0\ql{\f2 {\ltrch Prince Charles, born in 1948, prince of Wales and heir apparent to the throne of the United Kingdom of Great Britain and Northern Ireland. He is the son of Queen Elizabeth II and her husband, Philip Mountbatten, duke of Edinburgh. Charles\rquote s full name is Charl [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Story_Charles_Philip_Arthur_Windsor
        {
            get
            {
                return ResourceManager.GetString("Story_Charles_Philip_Arthur_Windsor", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs18\f2\cf0 \cf0\ql{\f2 {\ltrch Princess Diana (1961-1997), Princess of Wales from 1981 to 1997. Diana was born Diana Frances Spencer in Sandringham, Norfolk, England. Her father, Edward Spencer, was heir to an earldom, and her mother was the daughter of the 4th Baron Fermoy. Diana was educated at [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Story_Diana_Frances_Spencer
        {
            get
            {
                return ResourceManager.GetString("Story_Diana_Frances_Spencer", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs18\f2\cf0 \cf0\ql{\f2 {\ltrch Edward VII (1841-1910), king of the United Kingdom of Great Britain and Ireland and emperor of India (1901-1910). The Edwardian period is named after him.}\li0\ri0\sa0\sb0\fi0\ql\par}
        ///{\f2 \li0\ri0\sa0\sb0\fi0\ql\par}
        ///{\f2 {\ltrch Edward was born on November 9, 18 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Story_Edward_VII_Wettin
        {
            get
            {
                return ResourceManager.GetString("Story_Edward_VII_Wettin", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs18\f2\cf0 \cf0\ql{\f2 {\ltrch Edward VIII (1894-1972), king of the United Kingdom of Great Britain and Northern Ireland, and emperor of India (January 20-December 11, 1936), later known as the duke of Windsor.}\li0\ri0\sa0\sb0\fi0\ql\par}
        ///{\f2 \li0\ri0\sa0\sb0\fi0\ql\par}
        ///{\f2 {\ltrch Edward w [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Story_Edward_VIII_Windsor
        {
            get
            {
                return ResourceManager.GetString("Story_Edward_VIII_Windsor", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs18\f2\cf0 \cf0\ql{\f2 {\ltrch Elizabeth II, born in 1926, queen of the United Kingdom of Great Britain and Northern Ireland. Elizabeth Alexandra Mary was born in London, the first child of the duke and duchess of York, later King George VI and Queen Elizabeth. Her sister, Princess Margaret, was  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Story_Elizabeth_II_Alexandra_Mary_Windsor
        {
            get
            {
                return ResourceManager.GetString("Story_Elizabeth_II_Alexandra_Mary_Windsor", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs18\f2\cf0 \cf0\ql{\f2 {\ltrch George V (1865-1936), king of the United Kingdom of Great Britain and Northern Ireland, and emperor of India (1910-1936), of the house of Saxe-Coburg-Gotha (later changed to Windsor).}\li0\ri0\sa0\sb0\fi0\ql\par}
        ///{\f2 \li0\ri0\sa0\sb0\fi0\ql\par}
        ///{\f2 {\ltrch Geor [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Story_George_V_Windsor
        {
            get
            {
                return ResourceManager.GetString("Story_George_V_Windsor", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs18\f2\cf0 \cf0\ql{\f2 {\ltrch George VI (1895-1952), king of the United Kingdom of Great Britain and Northern Ireland (1936-1952), and emperor of India (1936-1947), of the house of Windsor. George was born at Sandringham House, Norfolk, on December 14, 1895, the second son of King George V, and  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Story_George_VI_Windsor
        {
            get
            {
                return ResourceManager.GetString("Story_George_VI_Windsor", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs18\f2\cf0 \cf0\ql{\f2 {\ltrch Princess Margaret (1930-2002), princess of Great Britain, younger sister of Queen Elizabeth II. She was born Margaret Rose on August 21, 1930, at Glamis Castle, Scotland, and was privately educated. After the death of her father, King George VI, in 1952, she assumed [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Story_Margaret_Rose_Windsor
        {
            get
            {
                return ResourceManager.GetString("Story_Margaret_Rose_Windsor", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Segoe UI.
        /// </summary>
        internal static string StoryFontFamily
        {
            get
            {
                return ResourceManager.GetString("StoryFontFamily", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à 14.
        /// </summary>
        internal static string StoryFontSize
        {
            get
            {
                return ResourceManager.GetString("StoryFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] WindsorSampleFile
        {
            get
            {
                object obj = ResourceManager.GetObject("WindsorSampleFile", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à .xaml.
        /// </summary>
        internal static string XamlExtension
        {
            get
            {
                return ResourceManager.GetString("XamlExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à *.xps.
        /// </summary>
        internal static string XpsExtension
        {
            get
            {
                return ResourceManager.GetString("XpsExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xps Files (.xps).
        /// </summary>
        internal static string XpsFiles
        {
            get
            {
                return ResourceManager.GetString("XpsFiles", resourceCulture);
            }
        }
    }
}
